### ISSUE TITLE
e2e tests are not robust enough

### ISSUE THREAD

**Issue by vitalii-bulyzhyn** [diffgram/diffgram#1248]
In some cases, e2e may fail because Walrus doesn't have enough resource to upload file. This happens on both local and cloud cypress. The problem is that sometimes tests may randomly fail, which makes debugging a lot more troublesome 

The easiest way to replicate this behaviour is to run walrus through the Docker and limit memory

**Comment by PJEstrada** [comment]
I've added 1G (6G to 7G) more of memory on the `deployments.yaml` for our gh action runners.

```
      containers:
      - name: runner
        env: []
        resources:
          limits:
            cpu: "3.5"
            memory: "7Gi"
          requests:
            cpu: "3.5"
            memory: "7Gi"
      - name: docker
        resources:
          limits:
            cpu: "3.5"
            memory: "7Gi"
          requests:
            cpu: "3.5"
            memory: "7Gi"  containers:
      - name: runner
        env: []
        resources:
          limits:
            cpu: "3.5"
            memory: "7Gi"
          requests:
            cpu: "3.5"
            memory: "7Gi"
      - name: docker
        resources:
          limits:
            cpu: "3.5"
            memory: "7Gi"
          requests:
            cpu: "3.5"
            memory: "7Gi"

```

I'll keep the issue open but that increase should help a bit. 


Another thing to keep in mind is that the walrus starts `waiting` if the memory usage spikes to like 75%, thus slowing down the uploads. Maybe we'll need to move that to a config to be able to deactivate it on the e2e test env.
