### ISSUE TITLE
encounter unhealthy container

### ISSUE THREAD

**Issue by JKYang01** [diffgram/diffgram#1615]
I have set up the cloud storage aws s3 and data base using AWS RDS(postgres)
when installing, I passed all the connection tests, however when build the docker container, it said db-1 is unhealthy.
The container log is empty so I cannot offering more information of that container. 
Here is my terminal looks like:

```
✓ Environment file written to: /home/bluespinach/workplace/diffgram/.env
Launching Diffgram...
WARN[0000] The "DIFFGRAM_MINIO_ACCESS_KEY_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DIFFGRAM_MINIO_ACCESS_KEY_SECRET" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DIFFGRAM_MINIO_ACCESS_KEY_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DIFFGRAM_MINIO_ACCESS_KEY_SECRET" variable is not set. Defaulting to a blank string. 
WARN[0000] /home/bluespinach/workplace/diffgram/docker-compose.yaml: `version` is obsolete 
[+] Running 101/10
 ✔ createbuckets Pulled                                                                    50.8s 
 ✔ eventhandlers Pulled                                                                   174.8s 
 ✔ default Pulled                                                                          19.4s 
 ✔ rabbitmq Pulled                                                                         46.5s 
 ✔ db_migration Pulled                                                                     19.4s 
 ✔ walrus Pulled                                                                           95.7s 
 ✔ minio Pulled                                                                            80.1s 
 ✔ db Pulled                                                                               74.9s 
 ✔ frontend Pulled                                                                         16.0s 
 ✔ dispatcher Pulled                                                                       37.3s 
[+] Running 11/11
 ✔ Network diffgram_default            Created                                              0.1s 
 ✘ Container diffgram-db-1             Error                                                2.7s 
 ✔ Container diffgram-rabbitmq-1       Healthy                                             31.7s 
 ✔ Container diffgram-minio-1          Healthy                                             31.7s 
 ✔ Container diffgram-createbuckets-1  Started                                             31.4s 
 ✔ Container diffgram-db_migration-1   Created                                              0.0s 
 ✔ Container diffgram-default-1        Created                                              0.0s 
 ✔ Container diffgram-walrus-1         Created                                              0.0s 
 ✔ Container diffgram-eventhandlers-1  Created                                              0.0s 
 ✔ Container diffgram-frontend-1       Created                                              0.0s 
 ✔ Container diffgram-dispatcher-1     Created                                              0.0s 
dependency failed to start: container diffgram-db-1 is unhealthy
✓ Diffgram Successfully Launched!
View the Web UI at: http://localhost:8085
Testing Connection...
[OK] Connection To Storage
[OK] Write Permissions
[OK] Read Permissions
Connection to S3 Successful!
```

I cannot open http://localhost:8085 it said problem loading page

```
Unable to connect

Firefox can’t establish a connection to the server at localhost:8085.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.
    
```
    
can anybody help to address what is happening in that db-1 container?

**Comment by JKYang01** [comment]
I found the image of this container is tianon/true which only contains true
`  POSTGRES_IMAGE=tianon/true `
and in the docker file there is a block of code doing the health check:
from docker-compose.yaml line 104
```
  db:
    image: ${POSTGRES_IMAGE}
    hostname: db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    - POSTGRES_DB=diffgram
    volumes:
    # Default INTERNAL_POSTGRES_DIR=/var/lib/postgresql/data:Z
    - ${POSTGRES_DATA_DIR:-./postgres-data}:${INTERNAL_POSTGRES_DIR:-/var/lib/postgresql/data}
    ports:
    - 5432:5432
```

can I comment out the health check part? 
what is those following set up for??? 
```
    - POSTGRES_HOST_AUTH_METHOD=trust
    - POSTGRES_DB=diffgram
```
should I modify the prostges_db as somthing else? (like my own db name?)
