### ISSUE TITLE
[backlog] Oracle Cloud Storage Support

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#286]
Option to support Oracle Cloud Storage
https://github.com/oracle/oci-python-sdk

Requires implementing similar to gcp, azure, aws ones here:
1) a connector, https://github.com/diffgram/diffgram/blob/master/walrus/methods/connectors/azure_connector.py
2) data tools,  https://github.com/diffgram/diffgram/blob/master/shared/data_tools_core_azure.py
3) tests, connection, read, write, etc.

For examples, there are implementations for gcp, azure, aws to look at:

Example Azure
The interfaces needed for joining existing unified APIs functions from L30 to L241  (after that is legacy)
https://github.com/diffgram/diffgram/blob/master/shared/data_tools_core_azure.py#L30
https://github.com/diffgram/diffgram/blob/master/shared/data_tools_core_azure.py#L241

Example GCP
https://github.com/diffgram/diffgram/blob/master/walrus/methods/connectors/google_cloud_storage_connector.py
https://github.com/diffgram/diffgram/blob/master/shared/data_tools_core_gcp.py

Example AWS
https://github.com/diffgram/diffgram/blob/master/walrus/methods/connectors/s3_connector.py
https://github.com/diffgram/diffgram/blob/master/shared/data_tools_core_s3.py

**Comment by anthony-sarkis** [comment]
![image](https://user-images.githubusercontent.com/18080164/133384280-2832e887-82fc-4bde-bd29-0ee2aa553783.png)

this is slightly out of date in terms of naming schemes but should give a general idea of architecture

**Comment by aniketzz** [comment]
Hi @anthony-sarkis,

I am able to establish a connection with OCI Bucket. I am getting an error after docker pull at **"Creating diffgram_default_1 ... error"**
![diffgram_install](https://user-images.githubusercontent.com/23217704/133749774-52d9b0eb-136f-4a37-83fb-6e32475ff60d.png)

**Comment by PJEstrada** [comment]
Hi @aniketzz,

Awesome, looks like you're almost there! I was checking the code for the `docker-compose.yaml` file and bascially the only volume that exists is this one:

```
    volumes:
    - ${GCP_SERVICE_ACCOUNT_FILE_PATH}:/gcp/gcp-service-account.json
```

So maybe the problem is that the `GCP_SERVICE_ACCOUNT_FILE_PATH` variable is not getting set to a long enough name. I would try to set it to something like `/dev/null`. You can check the `populate_env()` function in the `install.py` to see how we are generating it for other provicers different from `gcp`

**Comment by aniketzz** [comment]
Thanks, @PJEstrada,

I missed adding the OCI Credentials to `env_file` in `populate_env()`. Once I add The OCI credentials, the setup ran without any error.

**Comment by PJEstrada** [comment]
Cool, glad to hear it!

Make sure to also add them on the docker-compose.yaml, specifically on the `walrus` and `default` services. 

```
  walrus:
    image: gcr.io/diffgram-open-core/walrus:${DIFFGRAM_VERSION_TAG}
    ports:
    - "0.0.0.0:8082:8082"
    expose: [8080]
    depends_on:
    - db
    - default
    volumes:
    - ${GCP_SERVICE_ACCOUNT_FILE_PATH}:/gcp/gcp-service-account.json
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIFFGRAM_SYSTEM_MODE: "sandbox"
      DIFFGRAM_STATIC_STORAGE_PROVIDER:  ${DIFFGRAM_STATIC_STORAGE_PROVIDER}
      USER_PASSWORDS_SECRET:  ${USER_PASSWORDS_SECRET}
      SECRET_KEY:  ${SECRET_KEY}
      SERVICE_ACCOUNT_FULL_PATH: "/gcp/gcp-service-account.json"
      GOOGLE_APPLICATION_CREDENTIALS: "/gcp/gcp-service-account.json"
      CLOUD_STORAGE_BUCKET: ${CLOUD_STORAGE_BUCKET}
      ML__CLOUD_STORAGE_BUCKET: ${ML__CLOUD_STORAGE_BUCKET}
      DIFFGRAM_AWS_ACCESS_KEY_ID: ${DIFFGRAM_AWS_ACCESS_KEY_ID}
      DIFFGRAM_AWS_ACCESS_KEY_SECRET: ${DIFFGRAM_AWS_ACCESS_KEY_SECRET}
      DIFFGRAM_S3_BUCKET_NAME: ${DIFFGRAM_S3_BUCKET_NAME}
      ML__DIFFGRAM_S3_BUCKET_NAME: ${ML__DIFFGRAM_S3_BUCKET_NAME}
      DIFFGRAM_AZURE_CONNECTION_STRING: ${DIFFGRAM_AZURE_CONNECTION_STRING}
      DIFFGRAM_AZURE_CONTAINER_NAME: ${DIFFGRAM_AZURE_CONTAINER_NAME}
      ML__DIFFGRAM_AZURE_CONTAINER_NAME: ${ML__DIFFGRAM_AZURE_CONTAINER_NAME}
      MAILGUN_KEY: ${MAILGUN_KEY}
      WALRUS_SERVICE_URL_BASE: ${WALRUS_SERVICE_URL_BASE}
      INTER_SERVICE_SECRET: ${INTER_SERVICE_SECRET}
      PYTHONPATH: "/app/"
      DIFFGRAM_INSTALL_FINGERPRINT: ${DIFFGRAM_INSTALL_FINGERPRINT}
      DIFFGRAM_VERSION_TAG: ${DIFFGRAM_VERSION_TAG}
      DIFFGRAM_HOST_OS: ${DIFFGRAM_HOST_OS}
      DIFFGRAM_ERROR_SEND_TRACES_IN_RESPONSE: ${DIFFGRAM_ERROR_SEND_TRACES_IN_RESPONSE}
      DIFFGRAM_SERVICE_NAME: ${DIFFGRAM_SERVICE_NAME}
    entrypoint: ['python3', '-u', '/app/main.py']


  default:
    image: gcr.io/diffgram-open-core/default:${DIFFGRAM_VERSION_TAG}
    ports:
    - "0.0.0.0:8080:8080"
    expose: [8080]
    depends_on:
    - db
    volumes:
    - ${GCP_SERVICE_ACCOUNT_FILE_PATH}:/gcp/gcp-service-account.json
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIFFGRAM_SYSTEM_MODE: "sandbox"
      DIFFGRAM_STATIC_STORAGE_PROVIDER:  ${DIFFGRAM_STATIC_STORAGE_PROVIDER}
      USER_PASSWORDS_SECRET: ${USER_PASSWORDS_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      SERVICE_ACCOUNT_FULL_PATH: "/gcp/gcp-service-account.json"
      GOOGLE_APPLICATION_CREDENTIALS: "/gcp/gcp-service-account.json"
      CLOUD_STORAGE_BUCKET: ${CLOUD_STORAGE_BUCKET}
      ML__CLOUD_STORAGE_BUCKET: ${ML__CLOUD_STORAGE_BUCKET}
      DIFFGRAM_AWS_ACCESS_KEY_ID: ${DIFFGRAM_AWS_ACCESS_KEY_ID}
      DIFFGRAM_AWS_ACCESS_KEY_SECRET: ${DIFFGRAM_AWS_ACCESS_KEY_SECRET}
      DIFFGRAM_S3_BUCKET_NAME: ${DIFFGRAM_S3_BUCKET_NAME}
      ML__DIFFGRAM_S3_BUCKET_NAME: ${ML__DIFFGRAM_S3_BUCKET_NAME}
      DIFFGRAM_AZURE_CONNECTION_STRING: ${DIFFGRAM_AZURE_CONNECTION_STRING}
      DIFFGRAM_AZURE_CONTAINER_NAME: ${DIFFGRAM_AZURE_CONTAINER_NAME}
      ML__DIFFGRAM_AZURE_CONTAINER_NAME: ${ML__DIFFGRAM_AZURE_CONTAINER_NAME}
      MAILGUN_KEY: ${MAILGUN_KEY}
      WALRUS_SERVICE_URL_BASE: ${WALRUS_SERVICE_URL_BASE}
      INTER_SERVICE_SECRET: ${INTER_SERVICE_SECRET}
      PYTHONPATH: "/app/"
      DIFFGRAM_INSTALL_FINGERPRINT: ${DIFFGRAM_INSTALL_FINGERPRINT}
      DIFFGRAM_VERSION_TAG: ${DIFFGRAM_VERSION_TAG}
      DIFFGRAM_HOST_OS: ${DIFFGRAM_HOST_OS}
      DIFFGRAM_ERROR_SEND_TRACES_IN_RESPONSE: ${DIFFGRAM_ERROR_SEND_TRACES_IN_RESPONSE}
      DIFFGRAM_SERVICE_NAME: ${DIFFGRAM_SERVICE_NAME}
```
