### ISSUE TITLE
Walrus service exposing wrong port (8080 instead of 8082) in docker-compose.yaml

### ISSUE THREAD

**Issue by otecfuras** [diffgram/diffgram#746]
```
walrus:  
    image: gcr.io/diffgram-open-core/walrus:${DIFFGRAM_VERSION_TAG}
    ports:
    - "0.0.0.0:8082:8082"
    expose: [8080]
```
Is this intentional? It even conflicts with exposed port of *default* service.
