### ISSUE TITLE
Docker compose healthchecks fail when DB is from external system.

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#936]
When users install diffgram from an external system, they get failed healtchecks on docker compose startup.

This is due to the `depends_on` section on the `docker-compose.yaml`

```
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      db_migration:
        condition: service_completed_successfully
```

Since db is not working in this case, healthchecks fail. Preventing rest of containers to start.
